cb_rows: 6
cb_cols: 7
cb_dim: 0.034925
output_path: /home/humphreh/test_output.log
images: [ /home/humphreh/guvcview_image-1.jpg,
          /home/humphreh/guvcview_image-2.jpg,
          /home/humphreh/guvcview_image-3.jpg,
          /home/humphreh/guvcview_image-4.jpg,
          /home/humphreh/guvcview_image-5.jpg,
          /home/humphreh/guvcview_image-6.jpg,
          /home/humphreh/guvcview_image-7.jpg,
          /home/humphreh/guvcview_image-8.jpg,
          /home/humphreh/guvcview_image-9.jpg,
          /home/humphreh/guvcview_image-10.jpg,
          /home/humphreh/guvcview_image-11.jpg,
          /home/humphreh/guvcview_image-12.jpg,
          /home/humphreh/guvcview_image-13.jpg,
          /home/humphreh/guvcview_image-14.jpg,
          /home/humphreh/guvcview_image-16.jpg,
          /home/humphreh/guvcview_image-17.jpg,
          /home/humphreh/guvcview_image-18.jpg,
          /home/humphreh/guvcview_image-19.jpg,
          /home/humphreh/guvcview_image-20.jpg,
          /home/humphreh/guvcview_image-21.jpg,
          /home/humphreh/guvcview_image-22.jpg,
          /home/humphreh/guvcview_image-23.jpg,
          /home/humphreh/guvcview_image-24.jpg,
          /home/humphreh/guvcview_image-25.jpg,
          /home/humphreh/guvcview_image-26.jpg,
          /home/humphreh/guvcview_image-27.jpg,
          /home/humphreh/guvcview_image-28.jpg,
          /home/humphreh/guvcview_image-29.jpg,
          /home/humphreh/guvcview_image-30.jpg,
          /home/humphreh/guvcview_image-31.jpg,
          /home/humphreh/guvcview_image-32.jpg,
          /home/humphreh/guvcview_image-33.jpg,
          /home/humphreh/guvcview_image-34.jpg,
          /home/humphreh/guvcview_image-35.jpg]
